name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make
        env:
          CROWDIN_PROJECT: ${{ secrets.CROWDIN_PROJECT }}
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
      - name: Archive Phar
        uses: actions/upload-artifact@v3
        with:
          name: auth-cas.phar
          path: build/auth-cas.phar
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download math result for job 2
        uses: actions/download-artifact@v3
        with:
          name: auth-cas.phar
      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}
          artifacts: "build/auth-cas.phar"


